# Generated by Django 5.1 on 2024-09-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=266)),
                ('descriptions', models.CharField(max_length=500)),
                ('difficulties', models.CharField(blank=True, max_length=266, null=True)),
                ('solution', models.CharField(blank=True, max_length=266, null=True)),
                ('link', models.CharField(blank=True, max_length=266, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/')),
            ],
        ),
    ]
