# Generated by Django 5.1.2 on 2024-10-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployment_link',
            field=models.URLField(blank=True, max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/'),
        ),
    ]
